"""User Changes for ses

Revision ID: fa1653ae8f1a
Revises: 0001_create_all
Create Date: 2026-01-28 22:17:02.011120

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1653ae8f1a'
down_revision = '0001_create_all'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
